interface Manifest {
	config?: {
		fields?: ManifestConfigField[];
	};
}

interface ManifestConfigField {
	id: string;
	type: string;
}

interface ConfigNode {
	children: Map<string, ConfigNode>;
	type: string | null;
}

const manifestPath = new URL('../manifest.json', import.meta.url);
const generatedConfigDir = new URL('../src/gen/', import.meta.url);
const generatedConfigPath = new URL(
	'../src/gen/manifest.d.ts',
	import.meta.url,
);

const fieldTypeMap: Record<string, string> = {
	text: 'string',
	password: 'string',
	number: 'number',
	checkbox: 'boolean',
	dropdown: 'string',
	directory: 'string',
};

if (import.meta.main) {
	await generateManifestConfig();
}

export async function generateManifestConfig(): Promise<void> {
	const manifest = JSON.parse(
		await Deno.readTextFile(manifestPath),
	) as Manifest;
	const fields = manifest.config?.fields ?? [];
	const source = [
		'// Generated by scripts/generate-manifest-config.ts from manifest.json. Do not edit.',
		'',
		renderConfigType(fields),
		'',
	].join('\n');

	await Deno.mkdir(generatedConfigDir, { recursive: true });
	await Deno.writeTextFile(generatedConfigPath, source);
}

function renderConfigType(fields: ManifestConfigField[]): string {
	if (fields.length === 0) {
		return 'export interface ManifestConfig extends Record<string, never> {}';
	}

	const root: ConfigNode = {
		children: new Map(),
		type: null,
	};
	for (const field of fields) {
		addField(root, field);
	}

	return `export interface ManifestConfig ${renderNode(root, 0)}`;
}

function addField(root: ConfigNode, field: ManifestConfigField): void {
	const tsType = fieldTypeMap[field.type];
	if (tsType == null) {
		throw new Error(`Unsupported manifest config field type "${field.type}".`);
	}

	const parts = field.id.split('.');
	let node = root;
	for (const [index, part] of parts.entries()) {
		if (part === '') {
			throw new Error(`Invalid manifest config field id "${field.id}".`);
		}

		const isLeaf = index === parts.length - 1;
		let child = node.children.get(part);
		if (child == null) {
			child = {
				children: new Map(),
				type: null,
			};
			node.children.set(part, child);
		}

		if (isLeaf) {
			if (child.children.size > 0 || child.type != null) {
				throw new Error(`Duplicate manifest config field id "${field.id}".`);
			}
			child.type = tsType;
			return;
		}

		if (child.type != null) {
			throw new Error(`Conflicting manifest config field id "${field.id}".`);
		}
		node = child;
	}
}

function renderNode(node: ConfigNode, depth: number): string {
	const lines = ['{'];
	for (const [key, child] of node.children) {
		const value = child.type ?? renderNode(child, depth + 1);
		lines.push(`${'\t'.repeat(depth + 1)}${propertyKey(key)}: ${value};`);
	}
	lines.push(`${'\t'.repeat(depth)}}`);
	return lines.join('\n');
}

function propertyKey(key: string): string {
	return /^[$A-Z_a-z][$\w]*$/.test(key) ? key : JSON.stringify(key);
}
