import { Connector, type PollResult, upsert } from '@gety-ai/connector-sdk';
import type { ManifestConfig } from './gen/manifest.d.ts';

type SampleState = {
	run_count?: number;
};

const GETY_URL = 'https://gety.ai/';
const DOC_UPDATED_AT = '2026-05-12T00:00:00Z';

export default class GetySampleConnector extends Connector<
	ManifestConfig,
	SampleState
> {
	async *poll(): AsyncGenerator<PollResult, void, unknown> {
		const nextRunCount = (this.lastState?.run_count ?? 0) + 1;

		yield {
			updates: [
				upsert({
					id: 'gety-sample:introduction',
					title: 'Gety Sample Connector',
					content: [
						'This document was generated by the Gety sample connector.',
						'',
						'Gety is a private search engine for finding your own local and connected data.',
						'This sample demonstrates the minimum custom connector contract: a Deno class,',
						'an async generator poll method, upsert updates, a stable doc link, and a persisted state cursor.',
						'',
						`This connector has completed ${nextRunCount} poll invocation(s) in this Gety instance.`,
					].join('\n'),
					content_format: 'markdown',
					doc_updated_at: DOC_UPDATED_AT,
					doc_type: 'gety:sample',
					metadata: {
						url: GETY_URL,
						source: 'gety-sample-connector',
						run_count: nextRunCount,
					},
				}),
				upsert({
					id: 'gety-sample:development-notes',
					title: 'How to edit this connector',
					content: [
						'Edit src/index.ts, then run `deno task build`.',
						'The build writes dist/main.js, which is the manifest entry loaded by Gety.',
						'After installing this folder in Gety, use Restart to pick up changes immediately.',
					].join('\n'),
					content_format: 'markdown',
					doc_updated_at: DOC_UPDATED_AT,
					doc_type: 'gety:sample',
					metadata: {
						url: GETY_URL,
						source: 'gety-sample-connector',
					},
				}),
			],
			state: { run_count: nextRunCount },
		};
	}
}
